---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dafm5634/public_html/hotelinsight/
    - export DEPLOYPATH_PUBLIC=/home/dafm5634/public_html/hotelinsight/public/
    
    # Backup database (optional)
    - /bin/cp $DEPLOYPATH/.env $DEPLOYPATH/.env.backup.$(date +%Y%m%d_%H%M%S)
    
    # Copy files to deployment path (exclude .env)
    - /bin/cp -r app/ $DEPLOYPATH/
    - /bin/cp -r bootstrap/ $DEPLOYPATH/
    - /bin/cp -r config/ $DEPLOYPATH/
    - /bin/cp -r database/ $DEPLOYPATH/
    - /bin/cp -r lang/ $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -r resources/ $DEPLOYPATH/
    - /bin/cp -r routes/ $DEPLOYPATH/
    - /bin/cp -r storage/ $DEPLOYPATH/
    - /bin/cp -r vendor/ $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp artisan $DEPLOYPATH/
    - /bin/cp composer.json $DEPLOYPATH/
    - /bin/cp composer.lock $DEPLOYPATH/ 2>/dev/null || true
    
    # Preserve existing .env if exists, otherwise copy from example
    - if [ ! -f $DEPLOYPATH/.env ]; then /bin/cp .env.example $DEPLOYPATH/.env; fi
    
    # Update database configuration if .env exists
    - if [ -f $DEPLOYPATH/.env ]; then
        sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' $DEPLOYPATH/.env;
        sed -i 's|DB_DATABASE=.*|DB_DATABASE=dafm5634_hotelinsight|' $DEPLOYPATH/.env;
        sed -i 's|DB_USERNAME=.*|DB_USERNAME=dafm5634_ag|' $DEPLOYPATH/.env;
        sed -i 's|DB_PASSWORD=.*|DB_PASSWORD=Ag7us777__|' $DEPLOYPATH/.env;
        sed -i 's/APP_NAME=.*/APP_NAME="Hotel Insight"/' $DEPLOYPATH/.env;
        sed -i 's|APP_URL=.*|APP_URL=https://hotelinsight.dafam.cloud|' $DEPLOYPATH/.env;
        sed -i 's/APP_ENV=.*/APP_ENV=production/' $DEPLOYPATH/.env;
        sed -i 's/APP_DEBUG=.*/APP_DEBUG=false/' $DEPLOYPATH/.env;
        sed -i 's/# DB_HOST=127.0.0.1/DB_HOST=localhost/' $DEPLOYPATH/.env;
        sed -i 's/# DB_PORT=3306/DB_PORT=3306/' $DEPLOYPATH/.env;
        sed -i 's/# DB_DATABASE=dafm5634_hotelinsight/DB_DATABASE=dafm5634_hotelinsight/' $DEPLOYPATH/.env;
        sed -i 's/# DB_USERNAME=dafm5634_hotelinsight/DB_USERNAME=dafm5634_ag/' $DEPLOYPATH/.env;
        sed -i 's/# DB_PASSWORD=your_password_here/DB_PASSWORD=Ag7us777__/' $DEPLOYPATH/.env;
        echo "DB_CHARSET=utf8mb4" >> $DEPLOYPATH/.env;
        echo "DB_COLLATION=utf8mb4_unicode_ci" >> $DEPLOYPATH/.env;
      fi
    
    # Copy public files
    - /bin/cp -r public/* $DEPLOYPATH_PUBLIC/
    
    # Set permissions
    - /bin/chmod -R 755 $DEPLOYPATH/storage
    - /bin/chmod -R 755 $DEPLOYPATH/bootstrap/cache
    - /bin/chmod 644 $DEPLOYPATH/.env
    - /bin/chmod 755 $DEPLOYPATH/artisan
    
    # Clear cache
    - cd $DEPLOYPATH && php artisan config:clear
    - cd $DEPLOYPATH && php artisan cache:clear
    - cd $DEPLOYPATH && php artisan view:clear
    - cd $DEPLOYPATH && php artisan route:clear
    
    # Run migrations (if needed)
    - cd $DEPLOYPATH && php artisan migrate --force
    
    # Run seeders (if needed)
    - cd $DEPLOYPATH && php artisan db:seed --force
    
    # Create .htaccess in root (if needed)
    - echo "RewriteEngine On" > $DEPLOYPATH/.htaccess
    - echo "RewriteRule ^(.*)$ public/\$1 [L]" >> $DEPLOYPATH/.htaccess
    
    # Success message
    - echo "Deployment completed successfully!"
    - echo "Application deployed to: $DEPLOYPATH"
    - echo "Public URL: https://hotelinsight.dafam.cloud"
